"""
Summary: Tests for the path rules a GitHub repository is filtered by
before any file is downloaded: which folders and files are never read,
which dotfiles are the exceptions, how a lock file or a housekeeping
file is told from code, when a page is too long to have been written by
hand, and the order files are read in when a repository holds more than
a build takes.

This file is part of Extractium™
tests/test_github_files.py

Author(s): Gabriel Mongefranco.
Created: 2026-09-16
Last Modified: 2026-09-16
Notes: See README file for documentation and full license information.
"""

# Copyright © 2026 The Regents of the University of Michigan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

__author__ = "Gabriel Mongefranco, University of Michigan."
__copyright__ = "Copyright (C) 2026 The Regents of the University of Michigan"
__license__ = "GPLv3 or later"
__date__ = "2026-09-16"

import pytest

from extractium.sources import github_files as files


# ---------------------------------------------------------------------------
# Folders that are never read
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("path", [
    "third_party/sqlite/README.md", "thirdparty/x.py", "third-party/x.py", "3rdparty/x.py",
    "external/lib/x.c", "externals/x.c", "extern/x.c", "deps/x.py", "contrib/x.py",
    "submodules/x/README.md", "vendored/x.py", "vendors/x.py", "vendor/x.py",
    "generated/x.py", "__generated__/x.ts", "gen/x.go", "autogen/x.c", "autogenerated/x.c",
    "codegen/x.py", "src/generated/x.py",
])
def test_vendored_and_generated_folders_are_never_read(path):
    assert files.classify(path) is None


@pytest.mark.parametrize("path", [
    "tests/test_app.py", "test/x.py", "testing/x.py", "spec/x.rb", "specs/x.md",
    "__tests__/x.test.js", "tests/fixtures/page.html", "fixtures/x.json", "fixture/x.md",
    "testdata/x.txt", "test_data/x.csv", "golden/llms.txt", "snapshots/x.md",
    "__snapshots__/x.snap", "mocks/x.py", "__mocks__/x.js", "src/tests/x.py",
])
def test_test_folders_and_their_fixtures_are_never_read(path):
    assert files.classify(path) is None


@pytest.mark.parametrize("path, kind", [
    ("test_app.py", "code"),
    ("src/app_test.go", "code"),
    ("contest/rules.md", "documentation"),
    ("testimonials/README.md", "documentation"),
])
def test_only_folders_are_skipped_so_a_test_file_beside_its_code_is_read(path, kind):
    assert files.classify(path) == kind


@pytest.mark.parametrize("path", [
    "bin/tool.exe", "bin/report.md", "data/participants.csv", "data/README.md",
    "dist/app.js", "build/index.html", "node_modules/x/README.md", "target/x.rs",
    "coverage/index.html", "venv/lib/x.py", "site-packages/x.py", "renv/library/x/R/x.R",
])
def test_build_output_environments_and_data_folders_are_still_skipped(path):
    assert files.classify(path) is None


# ---------------------------------------------------------------------------
# Dotfiles and dot-folders
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("path", [
    ".git/config", ".venv/lib/x.py", ".idea/workspace.xml", ".vscode/settings.json",
    ".github/ISSUE_TEMPLATE/bug.md", ".github/CODEOWNERS", ".github/copilot-instructions.md",
    ".gitignore", ".gitattributes", ".editorconfig", ".pre-commit-config.yaml",
    ".claude/settings.json", ".Rprofile", ".env", ".env.local", "src/.hidden/x.py",
    "sub/.github/workflows/ci.yml",
])
def test_every_dot_prefixed_folder_and_file_is_skipped(path):
    assert files.classify(path) is None


@pytest.mark.parametrize("path, kind", [
    (".github/workflows/ci.yml", "manifest"),
    (".github/workflows/release.yaml", "manifest"),
    (".gitmodules", "manifest"),
    (".env.example", "manifest"),
    (".env.sample", "manifest"),
    (".env.template", "manifest"),
])
def test_the_dotfiles_that_document_a_project_are_the_exceptions(path, kind):
    assert files.classify(path) == kind


# ---------------------------------------------------------------------------
# Files that are never read, by name
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("path", [
    "include/app.h", "src/app.hpp", "src/app.hh", "src/app.hxx", "src/app.inl",
    "src/app.tpp", "src/app.ipp",
])
def test_c_and_cpp_headers_are_skipped(path):
    assert files.classify(path) is None


@pytest.mark.parametrize("path", ["src/app.c", "src/app.cpp", "src/app.cc"])
def test_c_and_cpp_source_files_are_still_code(path):
    assert files.classify(path) == "code"


@pytest.mark.parametrize("path", [
    "proto/api.pb.go", "proto/api.pb.cc", "proto/api.pb.h", "api_pb2.py", "api_pb2_grpc.py",
    "Form1.g.cs", "Form1.Designer.cs", "schema.generated.ts", "app.min.js", "site.min.css",
    "app.bundle.js", "vendor.chunk.js", "lib.umd.js", "lib.esm.js", "app.js.map",
    "logo.svg",
])
def test_generated_files_are_recognised_by_name(path):
    assert files.classify(path) is None


@pytest.mark.parametrize("path", [
    "sqlite3.c", "sqlite3.h", "sqlite3ext.h", "cJSON.c", "cJSON_Utils.h", "stb_image.h",
    "miniz.c", "jquery.js", "jquery-3.6.0.min.js", "bootstrap.css", "bootstrap.bundle.js",
    "lodash.js", "moment.js", "d3.js", "d3-array.js", "three.js",
])
def test_single_file_libraries_projects_copy_in_are_skipped(path):
    assert files.classify(path) is None


@pytest.mark.parametrize("path", ["shell.c", "d3chart.js", "threeway.js", "momentum.py"])
def test_a_neighbour_or_a_look_alike_of_a_library_is_still_read(path):
    assert files.classify(path) == "code"


@pytest.mark.parametrize("path", [
    "LICENSE", "LICENSE.txt", "LICENSE.md", "LICENCE", "COPYING", "COPYING.LESSER",
    "LICENSE-MIT", "LICENSE.Apache-2.0.txt", "NOTICE", "NOTICE.txt", "NOTICE.md",
    "CITATION.cff", "CITATION.bib", "CITATION", "CODE_OF_CONDUCT.md",
    "CLAUDE.md", "AGENTS.md", "AGENT.md", "CONVENTIONS.md", "CODEX.md", "GEMINI.md",
    "SKILLS.md", "copilot-instructions.md", "docs/LICENSE.md", "src/AGENTS.md",
])
def test_licence_notice_citation_conduct_and_agent_instruction_files_are_skipped(path):
    assert files.classify(path) is None


@pytest.mark.parametrize("path, kind", [
    ("agent.py", "code"),
    ("agents.py", "code"),
    ("notice.py", "code"),
    ("skills.R", "code"),
    ("licenses/third-party.md", "documentation"),
    ("licensing-guide.md", "documentation"),
])
def test_a_code_file_or_a_prose_file_that_merely_sounds_like_housekeeping_is_read(path, kind):
    assert files.classify(path) == kind


@pytest.mark.parametrize("path", [
    "README", "README.md", "README.rst", "docs/README.md", "CHANGELOG.md", "CHANGES",
    "HISTORY.md", "CONTRIBUTING.md", "SECURITY.md", "AUTHORS", "CONTRIBUTORS.md",
    "GOVERNANCE.md", "SUPPORT.md", "MAINTAINERS", "docs/guide.md", "notes.txt",
    "manual.rst", "book.adoc",
])
def test_the_documentation_people_search_is_still_read(path):
    assert files.classify(path) == "documentation"


@pytest.mark.parametrize("path", [
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "poetry.lock", "pdm.lock", "uv.lock",
    "Cargo.lock", "Gemfile.lock", "composer.lock", "Pipfile.lock", "packages.lock.json",
    "requirements-lock.txt", "requirements.lock", "go.sum", "gradle.lockfile", "bun.lockb",
    "flake.lock", "sub/package-lock.json",
])
def test_lock_files_are_skipped_wherever_they_are(path):
    assert files.classify(path) is None


@pytest.mark.parametrize("path, kind", [
    ("renv.lock", "manifest"),
    ("requirements.txt", "manifest"),
    ("requirements-dev.txt", "manifest"),
    ("lock.py", "code"),
    ("lockfile.py", "code"),
    ("deadlock.md", "documentation"),
    ("lockfile.md", "documentation"),
    ("docs/locking.md", "documentation"),
])
def test_lock_is_a_word_in_the_name_and_renv_lock_is_the_exception(path, kind):
    assert files.classify(path) == kind


@pytest.mark.parametrize("path", [
    "settings.toml", "config.yml", "config.yaml", "data.json", "app.ini", "setup.cfg.bak",
    "app.conf", "app.properties", "schema.xml", "styles/main.css", "styles/main.scss",
    "styles/main.sass", "styles/main.less", "queries/highlights.scm",
])
def test_settings_styling_and_query_files_are_not_read(path):
    assert files.classify(path) is None


@pytest.mark.parametrize("path", [
    "pyproject.toml", "Cargo.toml", "package.json", "composer.json", "codemeta.json",
    "environment.yml", "conda.yaml", "docker-compose.yml", "pom.xml", "setup.cfg",
    "app.csproj", "Lib.podspec",
])
def test_a_manifest_wins_over_the_settings_extension_it_carries(path):
    assert files.classify(path) == "manifest"


@pytest.mark.parametrize("path", [".env", "id_rsa", "server.pem", "keys/app.key", "cert.pfx"])
def test_anything_holding_a_credential_is_skipped(path):
    assert files.classify(path) is None


def test_a_path_with_no_name_or_ending_in_a_slash_is_nothing():
    assert files.classify("") is None
    assert files.classify("docs/") is None


# ---------------------------------------------------------------------------
# Generated by size
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("path, size, generated", [
    ("docs/index.html", 2_800_000, True),
    ("docs/index.htm", 500_001, True),
    ("docs/index.html", 500_000, False),
    ("app.js", 600_000, True),
    ("app.mjs", 600_000, True),
    ("app.cjs", 600_000, True),
    ("app.jsx", 600_000, True),
    ("app.js", 4_000, False),
    ("manual.md", 2_800_000, False),
    ("app.py", 2_800_000, False),
    ("docs/index.html", None, False),
])
def test_a_page_or_script_too_long_to_be_hand_written_is_generated(path, size, generated):
    assert files.is_generated_by_size(path, size) is generated


# ---------------------------------------------------------------------------
# Reading order
# ---------------------------------------------------------------------------

def test_files_are_read_root_readme_first_then_shallowest_and_code_last():
    paths = [
        "src/app.py", "docs/guide.md", "package.json", "docs/README.md", "README.md",
        "src/lib/deep.py", "docs/plan.docx", "examples/README.md", "app.py", "docs/a/b/notes.md",
    ]
    ranked = sorted(paths, key=lambda path: files.read_priority(path, files.classify(path)))

    assert ranked == [
        "README.md",
        "docs/README.md", "examples/README.md",
        "docs/guide.md", "docs/a/b/notes.md",
        "package.json",
        "docs/plan.docx",
        "app.py", "src/app.py", "src/lib/deep.py",
    ]


def test_read_priority_says_how_deep_a_file_sits_and_carries_its_path():
    assert files.read_priority("README.md", "documentation") == (0, 0, "readme.md")
    assert files.read_priority("docs/README.md", "documentation") == (1, 1, "docs/readme.md")
    assert files.read_priority("docs/a/guide.md", "documentation") == (2, 2, "docs/a/guide.md")
    assert files.read_priority("src/app.py", "code") == (5, 1, "src/app.py")


def test_a_kind_outside_the_reading_order_sorts_last():
    assert files.read_priority("x", None)[0] == len(files.READ_ORDER)


def test_the_reading_order_names_every_kind_classify_returns():
    assert set(files.READ_ORDER) >= {"documentation", "manifest", "document", "code"}
